
@startuml pert2
left to right direction

actor as user as user
package Restoran {
    actor servent as servent
    actor chief as chief
}

package Restoran {
    usecase "Pesan Menu" as u1
    usecase "Bayar pesanan" as u2
    usecase "Melaporkan pesanan" as u3
    usecase "Memasak pesanan" as u4
}

user --> U1
user --> U2
user --> U3
user --> U4

@enduml
